# Etapa 1: Compilar la app de React con Node
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor web ligero (Nginx) para entregar los archivos estáticos
FROM nginx:alpine AS final
# Copiamos la carpeta 'dist' que generó Vite al directorio de Nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]